name: Backend Go CI/CD

on:
  push:
    branches:
      - main
    # 仅当以下路径下的文件发生变化时，才运行此工作流
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci-cd.yml' # 工作流文件本身变化也要触发
  pull_request:
    paths:
      - 'backend/**'